//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Weservice.Common
{
    using System;
    using System.Collections.Generic;
    
    public partial class dt_wx_token
    {
        public int id { get; set; }
        public string info_type { get; set; }
        public Nullable<System.DateTime> last_time { get; set; }
        public Nullable<int> expires_in { get; set; }
        public string appid { get; set; }
        public string token { get; set; }
    }
}
